name: Deploy Movie Generator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build with API key
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: |
        # Create a config file with the API key for the build
        echo "const CONFIG = { TMDB_API_KEY: '$TMDB_API_KEY' };" > config.js
        
        # Update the frontend to use the config
        sed -i 's|const API_BASE_URL = .*|const API_BASE_URL = "https://api.themoviedb.org/3";|' script.js
        sed -i 's|fetch(`${API_BASE_URL}/genres`)|fetch(`${API_BASE_URL}/genre/movie/list?api_key=${CONFIG.TMDB_API_KEY}`)|' script.js
        sed -i 's|fetch(`${API_BASE_URL}/discover|fetch(`${API_BASE_URL}/discover/movie?api_key=${CONFIG.TMDB_API_KEY}&sort_by=popularity.desc|' script.js
        sed -i 's|fetch(`${API_BASE_URL}/search|fetch(`${API_BASE_URL}/search/movie?api_key=${CONFIG.TMDB_API_KEY}&query|' script.js
        sed -i 's|fetch(`${API_BASE_URL}/movie/|fetch(`${API_BASE_URL}/movie/|' script.js
        sed -i 's|fetch(`${API_BASE_URL}/movie/${movie.id}`)|fetch(`${API_BASE_URL}/movie/${movie.id}?api_key=${CONFIG.TMDB_API_KEY}`)|' script.js
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
